# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6214ab7215d37880bd109063ab93c95c92c52a67b421508a72ab89063200b66117b739be4afc82e5738127259a8ffc45ef8f87fa27111f9a2c2c95b5c3a94a2

test:
  secret_key_base: 65fcc084a031e5bb9e405bc3b520201fdcc04726227fc93b0dabe9c78bf9ffed5a982d7a0eec62fc018999202bf3809657cb817ad3052c3a89bcf1e642f4dbad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
